version: '3.8'

services:
  eth-node:
    build: .
    container_name: eth-dev-node
    environment:
      - NODE_PASS=password123
    ports:
      - "8545:8545"
    volumes:
      - eth-data:/eth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eth-data: