version: '3.8'

services:
  eth-node:
    build: .
    container_name: eth-dev-node
    env_file: .env
    environment:
      - ACCOUNT_PASSWORD=${NODE_PASS}
    ports:
      - "${NODE1_HTTP_PORT}:8545"  # HTTP RPC
      - "${NODE1_WS_PORT}:8546"    # WS
      - "${NODE1_P2P_PORT}:30303"  # P2P
    volumes:
      - eth-data:/eth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eth-data: