version: '3.8'

services:
  eth-node:
    build: .
    container_name: eth-dev-node
    environment:
      - NETWORK_ID=1337
      - ACCOUNT_PASSWORD=tu_contraseña_segura
    ports:
      - "8545:8545"  # HTTP RPC
      - "8546:8546"  # WS
      - "30303:30303"  # P2P
    volumes:
      - eth-data:/eth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eth-data: